CREATE DATABASE escola;
SHOW DATABASES;
USE escola;

CREATE TABLE aluno (
	id int,
    nome varchar(255)
);

SHOW TABLES;
DESC aluno;

INSERT INTO aluno (id, nome) VALUES (1, 'Joao da Silva');
INSERT INTO aluno (id, nome) VALUES (2, 'Maria da Silva');
INSERT INTO aluno VALUES (3, 'Luiz Carlos Almeida');
INSERT INTO aluno VALUES (4, 'Luiza Pereira');
INSERT INTO aluno VALUES (5, 'Beltrano Carlos Xavier');

SELECT * FROM ALUNO;
SELECT id, nome FROM aluno;
SELECT id, nome FROM aluno;
SELECT id FROM aluno;
SELECT nome FROM aluno;
SELECT id AS codigo from aluno;
SELECT nome AS 'Nome do Aluno' FROM aluno;
SELECT id AS 'Codigo do Aluno', nome AS 'Nome do Aluno' FROM aluno;

SELECT COUNT(*) FROM aluno;
SELECT COUNT(*) AS 'Total de Alunos' FROM aluno;

SELECT id, nome FROM aluno;
SELECT id, upper(nome) FROM aluno;
SELECT id, upper(nome) AS NOME FROM aluno;
SELECT id AS 'Código', upper(nome) AS 'Nome do Aluno' FROM aluno;

SELECT id, lower(nome) FROM aluno;
SELECT id AS 'Código', lower(nome) AS 'Nome do Aluno' FROM aluno;

SELECT * FROM aluno;
SELECT * FROM aluno ORDER BY nome;
SELECT * FROM aluno ORDER BY id;
SELECT * FROM aluno ORDER BY id ASC;
SELECT * FROM aluno ORDER BY id DESC;
SELECT * FROM aluno ORDER BY nome;
SELECT * FROM aluno ORDER BY nome ASC;

SELECT id AS 'Código', nome AS 'Nome do Aluno' FROM aluno ORDER BY nome ASC;
SELECT id AS 'Código', upper(nome) AS 'Nome do Aluno' FROM aluno ORDER BY nome ASC;

SELECT * FROM ALUNO WHERE ID=1;
SELECT * FROM ALUNO WHERE ID=1 OR ID=2;
SELECT * FROM ALUNO WHERE ID=1 OR ID=2 OR ID=3;
SELECT * FROM ALUNO WHERE ID>0 AND ID<4;
SELECT * FROM ALUNO WHERE ID>=1 AND ID<=3;
SELECT * FROM ALUNO WHERE ID>=1 AND ID<=3 OR ID<=5;

SELECT * FROM ALUNO WHERE NOME='Joao da Silva';
SELECT * FROM ALUNO WHERE NOME='joao da silva';
SELECT * FROM ALUNO WHERE NOME='joao da SILVA';
SELECT * FROM ALUNO WHERE NOME='JOAO DA SILVA';
SELECT * FROM ALUNO WHERE NOME='JOAO';
SELECT * FROM ALUNO WHERE LENGTH(NOME) > 10;
SELECT * FROM ALUNO WHERE LENGTH(NOME) > 15;
SELECT * FROM ALUNO WHERE LENGTH(NOME) < 20;
SELECT * FROM ALUNO WHERE LENGTH(NOME) < 14;

SELECT * FROM ALUNO WHERE NOME LIKE 'joao';
SELECT * FROM ALUNO WHERE NOME LIKE 'JOAO%';
SELECT * FROM ALUNO WHERE NOME LIKE 'LUIZ%';
SELECT * FROM ALUNO WHERE NOME LIKE '%SILVA%';
SELECT ID AS CODIGO, NOME AS 'SOBRENOME SILVA' FROM ALUNO WHERE NOME LIKE '%SILVA';
SELECT ID AS CODIGO, NOME AS 'SOBRENOME SILVA' FROM ALUNO WHERE NOME LIKE '%silva' ORDER BY NOME DESC;

SELECT * FROM ALUNO WHERE NOME LIKE '%DA%'; 
SELECT * FROM ALUNO WHERE NOME LIKE '% DA %';
SELECT COUNT(*) AS 'Total de Silvas' FROM ALUNO WHERE NOME LIKE '%SILVA%';

SELECT version();
SELECT version() AS 'Versão do MySQL';

SELECT ASCII('A');
SELECT ASCII('B');
SELECT ASCII('a');
SELECT ASCII('b');

SELECT CHAR(65);
SELECT CHAR(66);
SELECT CHAR(97);
SELECT CHAR(98);

SELECT CURRENT_DATE();
SELECT CURRENT_DATE() AS 'Data Atual';
SELECT CURDATE();
SELECT CURDATE() AS 'Data Atual';

SELECT CURRENT_TIME();
SELECT CURRENT_TIME;
SELECT CURTIME();
SELECT CURTIME() AS 'Hora Atual';

SELECT CURDATE(), CURTIME();
SELECT CURDATE() AS 'Data Atual', CURTIME() AS 'Hora Atual';

SELECT NOW();
SELECT NOW() AS 'Data e Hora Atual';

SELECT DAYOFWEEK(NOW());
SELECT DAYOFMONTH(NOW());
SELECT DAYOFMONTH(NOW()) AS 'Hoje é';
SELECT DAYOFYEAR(NOW());
SELECT DAY(NOW());
SELECT MONTH(NOW());
SELECT YEAR(NOW());
SELECT DAY(NOW()), MONTH(NOW()), YEAR(NOW());
SELECT DAY(NOW()) AS 'DIA', MONTH(NOW()) AS 'MÊS', YEAR(NOW()) AS 'ANO';
SELECT DAYNAME(NOW());
SELECT MONTHNAME(NOW());
SELECT DAYNAME(NOW()) AS 'DIA', MONTHNAME(NOW()) AS 'MÊS', YEAR(NOW()) AS 'ANO';
SELECT 'PONTA GROSSA, ', DAY(NOW()), ' DE ', MONTHNAME(NOW()), ' DE ', YEAR(NOW());

SELECT CONCAT('BOM', 'DIA', 'BRASIL');
SELECT CONCAT(1,2,3);
SELECT CONCAT('PONTA GROSSA, ', DAY(NOW()), ' DE ', MONTHNAME(NOW()), ' DE ', YEAR(NOW()));
SELECT CONCAT('PONTA GROSSA, ', DAY(NOW()), ' DE ', MONTHNAME(NOW()), ' DE ', YEAR(NOW())) AS 'Data de Hoje';

SELECT DATE_FORMAT(NOW(), '%d %b %Y');
SELECT DATE_FORMAT(NOW(), '%d %M %Y');
SELECT DATE_FORMAT(NOW(), '%d %m %Y');
SELECT DATE_FORMAT(NOW(), '%d %c %Y');
SELECT DATE_FORMAT(NOW(), '%a %M %Y');
SELECT DATE_FORMAT(NOW(), '%W %M %Y');
SELECT DATE_FORMAT(NOW(), '%W %M %y');

SELECT DATE_FORMAT(NOW(), '%h:%i %p');
SELECT DATE_FORMAT(NOW(), '%H:%i');
SELECT DATE_FORMAT(NOW(), '%H:%i:%s');
SELECT DATE_FORMAT(NOW(), '%T');

SELECT USER();

SELECT 1+2+3;
SELECT 1+2+3 AS TOTAL;
SELECT 1+2, 3.14 *2, 9-4, 5/4;
SELECT POWER(3,2);
SELECT POWER(3,3);
SELECT SQRT(9);
SELECT 5/3;
SELECT 5 DIV 3;
SELECT 5 % 3;
SELECT 5 mod 3;
SELECT MOD(5,3);
SELECT ABS(-55);
SELECT ABS(-1);
SELECT ABS(0);
SELECT ABS(55);
SELECT SIN(45);
SELECT COS(30);
SELECT TAN(15);
SELECT PI();
SELECT FLOOR(4.5);
SELECT CEIL(4.1);
SELECT CEILING(4.1);
SELECT ROUND(4.1);
SELECT ROUND(4.5);
SELECT ROUND(4.9);
SELECT RADIANS(180);
SELECT DEGREES(3.14159);
SELECT ROUND(DEGREES(3.14159));
SELECT RAND();
SELECT RAND() * 100;
SELECT ROUND(RAND() * 100);